apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-service
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      containers:
        - name: mail-service
          image: "mongo:4.2.17-bionic"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: MAIL_DOMAIN
              value: ""
            - name: MAIL_HOST
              value: "mailhog"
            - name: MAIL_PORT
              value: "1025"
            - name: MAIL_ENCRYPTION
              value: "none"
            - name: MAIL_USERNAME
              value: ""
            - name: MAIL_PASSWORD
              value: ""
            - name: MAIL_FROM_NAME
              value: "Nam Nguyen"
            - name: MAIL_FROM_ADDRESS
              value: "nam.nguyen@mydomain.com"
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      name: main-port
      port: 27017
      targetPort: 27017
